version: '3'
services:
  serverone:
      build:
        context: ../localhost/8081
        dockerfile: Dockerfile
      ports:
        - 8081:8081
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8081

  servertwo:
      build:
        context: ../localhost/8082
        dockerfile: Dockerfile
      ports:
        - 8082:8082
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8082

  serverthree:
      build:
        context: ../localhost/8083
        dockerfile: Dockerfile
      ports:
        - 8083:8083
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8083

  serverfive:
      build:
        context: ../localhost/8085
        dockerfile: Dockerfile
      ports:
        - 8085:8085
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8085
  
  serversix:
      build:
        context: ../localhost/8086
        dockerfile: Dockerfile
      ports:
        - 8086:8086
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8086

  serverseven:
      build:
        context: ../localhost/8087
        dockerfile: Dockerfile
      ports:
        - 8087:8087
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8087

  servereight:
      build:
        context: ../localhost/8088
        dockerfile: Dockerfile
      ports:
        - 8088:8088
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8088

  servernine:
      build:
        context: ../localhost/8089
        dockerfile: Dockerfile
      ports:
        - 8089:8089
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8089