version: '3'
services:
  serverone:
      build:
        context: ../localhost/8081
        dockerfile: Dockerfile
      ports:
        - 8081:8081
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8081

  servertwo:
      build:
        context: ../localhost/8082
        dockerfile: Dockerfile
      ports:
        - 8082:8082
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8082

  serverthree:
      build:
        context: ../localhost/8083
        dockerfile: Dockerfile
      ports:
        - 8083:8083
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8083

  serverfour:
      build:
        context: ../localhost/8085
        dockerfile: Dockerfile
      ports:
        - 8085:8085
      volumes:
      - ../../:/go/src/github.com/seipan/mylb/testserver/localhost/8085