name: E2E Test for TestServer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up testserver
      run: |
        cd testserver
        make up

    - name: Check the 8081
      uses: jtalk/url-health-check-action@v3
      with:
        url: http://localhost:8081

    - name: Check the 8082
      uses: jtalk/url-health-check-action@v3
      with:
        url: http://localhost:8082
    
    - name: Check the 8083
      uses: jtalk/url-health-check-action@v3
      with:
        url: http://localhost:8083
    
    - name: Check the 8084
      uses: jtalk/url-health-check-action@v3
      with:
        url: http://localhost:8084
    