name: E2E Test for TestServer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up testserver
      run: |
        cd testserver
        make re

    - name: Check the 8081
      uses: jtalk/url-health-check-action@v4
      with:
        url: http://localhost:8081

    - name: Check the 8082
      uses: jtalk/url-health-check-action@v4
      with:
        url: http://localhost:8082
    
    - name: Check the 8083
      uses: jtalk/url-health-check-action@v4
      with:
        url: http://localhost:8083
    
    - name: Check the 8085
      uses: jtalk/url-health-check-action@v4
      with:
        url: http://localhost:8085
    
    - name: Check the 8086
      uses: jtalk/url-health-check-action@v4
      with:
        url: http://localhost:8086
    
    - name: Check the 8087
      uses: jtalk/url-health-check-action@v4
      with:
        url: http://localhost:8087
    
    - name: Check the 8088
      uses: jtalk/url-health-check-action@v4
      with:
        url: http://localhost:8088
        
    - name: Check the 8089
      uses: jtalk/url-health-check-action@v4
      with:
        url: http://localhost:8089