name: E2E Test for LoadBalancer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up testserver
      run: |
        cd testserver
        make re
    
    - name: set up loadbalancer
      run: |
        make run

    - name: Check the 8080
      uses: jtalk/url-health-check-action@v3
      with:
        url: http://localhost:8080